# This is a basic workflow to help you get started with Actions

name: Main Pipeline

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  hoist:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: shrikantrshelke/shared-workflow/.github/workflows/build.yml@main
      # Runs a single command using the runners shell
      #- name: Build Docker Image
      #  run: |
      #    docker build . --file infra/Dockerfile
          
      #- name: Push Image
      #  run: echo "Push Image to ECR"
