# This is a basic workflow to help you get started with Actions

name: Unit_Test

# Controls when the workflow will run
on:
  workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: yq - portable yaml processor
      # You may pin to the exact commit or the version.
      # uses: mikefarah/yq@87cba2ecbeaecf860efcceb66deab46ae030ce1e
        uses: mikefarah/yq@v4.30.6
        with:
          # The Command which should be run
          cmd: |
            myarr=$(yq '.testing.unit.file | @csv'  infra/pipeline.yml)
            IFS=","
            for test_case in $myarr
            do
                echo "Runnng testcase: $test_case"
            done"


